= Tahu Component
:doctitle: Tahu
:shortname: tahu
:artifactid: camel-tahu
:description: Sparkplug B Edge Node and Host Application support over MQTT using Eclipse Tahu
:since: 4.8
:supportlevel: Preview
:tabs-sync-option:
:component-header: Both producer and consumer are supported

*Since Camel {since}*

*{component-header}*

The Tahu component adapts the 
https://projects.eclipse.org/projects/iot.tahu[Eclipse Tahu] library for Camel.
This component supports creating Sparkplug Edge Nodes, Devices, and Host
Applications as described by https://projects.eclipse.org/projects/iot.sparkplug[Eclipse Sparkplug]
using Sparkplug B payload encoding.

For more information regarding Sparkplug concepts and required behavior, consult the
https://www.eclipse.org/tahu/spec/sparkplug_spec.pdf[Sparkplug 3.0.0 Specification]

NOTE: Neither the use of the Eclipse Tahu library nor the Camel Tahu Component
implies Sparkplug 3.0.0 specification compliance. While it *should* be possible
to create Sparkplug 3.0.0-compliant applications using the Camel Tahu Component,
no claims or guarantees are expressed or implied.

Maven users will need to add the following dependency to their `pom.xml`
for this component:

[source,xml]
----
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>{artifactid}</artifactId>
    <version>x.x.x</version>
    <!-- use the same version as your Camel core version -->
</dependency>
----

== URI format

=== Edge Nodes and Devices (Producers)

.Edge Node and Device endpoints, where `groupId`, `edgeNodeId`, and `deviceId` are the Sparkplug Group, Edge Node, and Device IDs describing the Edge Node or Device.
-----
tahu://groupId/edgeNodeId[/deviceId]?options
-----

.Edge Node Producer for Group 'Basic' and Edge Node 'EdgeNode' using MQTT Client ID 'EdgeClient1' connecting to Host Application 'BasicHostApp'
[caption="Example: "]
------
tahu://Basic/EdgeNode?clientId=EdgeClient1&primaryHostId=BasicHostApp&deviceIds=D2,D3,D4
------

.Device Producers for Devices 'D2', 'D3', and 'D4' connected to Edge Node 'EdgeNode' in Group 'Basic', i.e. the Devices of the Edge Node in the example above
[caption="Example: "]
------
tahu://Basic/EdgeNode/D2
tahu://Basic/EdgeNode/D3
tahu://Basic/EdgeNode/D4
------

=== Host Applications (Consumers)

.Host Application endpoints, where `hostId` is the Sparkplug Host Application ID
-----
tahu://hostId?options
-----

.Host Application Consumer for Host App 'BasicHostApp' using MQTT Client ID 'HostClient1'
[caption="Example: "]
------
tahu:BasicHostApp?clientId=HostClient1
------

== Endpoints

Tahu component endpoints describe a Sparkplug Edge Node, Device, or Host
Application. All Sparkplug specification requirements must be observed
when defining the endpoint URIs, including allowed characters in names,
uniqueness in IDs, etc. Device IDs can include additional hierarchy with
'/' characters as allowed by the specification.

Tahu Edge Node and Device endpoints only allow Producers to be created.
Tahu Host Application endpoints only allow Consumers to be created.

// component-configure options: START

// component-configure options: END

// component options: START
include::partial$component-configure-options.adoc[]
include::partial$component-endpoint-options.adoc[]
// component options: END

// endpoint options: START

// endpoint options: END

// component headers: START
include::partial$component-endpoint-headers.adoc[]
// component headers: END


== Usage

The Sparkplug 3.0.0 specification requires Sparkplug B MQTT message payloads to follow 
a Google Protobuf format with an specific structure and message order.
Many of these requirements necessitate careful Tahu Component and Endpoint
configurations.

=== Component Configuration

Tahu Component configuration is primarily composed of MQTT Server connection
information. These properties may be configured on Endpoint URIs or the Tahu
Component to cover all Endpoints created using that Component instance.

The `servers` property is a comma-separated list with the following syntax:

----
MqttServerName:[MqttClientId:](tcp|ssl)://hostname[:port],...
----

This gives a unique server name to each MQTT Server as well as its connection
scheme (`tcp` or `ssl`), hostname, and optionally the port number. A 
connection-specific MQTT Client ID may also be assigned when connecting to
this particular server. MQTT Client ID uniqueness requirements apply.

A common MQTT Client ID may also be configured through the `clientId` property
and will apply to all MQTT Server connections NOT specifying a connection-specific
`MqttClientId` in the `servers` list. Should neither the `clientId` nor the
`MqttClientId` be set, a random MQTT Client ID will be generated prefaced by
"Camel".

MQTT Client IDs are limited to 23 characters in MQTT v3.1. However, MQTT v3.1.1 increased that
limit to 256 characters. When connecting to MQTT Servers only supporting v3.1,
setting the `checkClientIdLength` flag to `true` will add a 23-character length
check to ensure proper Client ID lengths. This is a configuration-time check and
is not required to connect to MQTT v3.1 Servers.

MQTT Server authentication can be configured using the `username` and `password`
properties. TLS configuration can also be configured by providing an
`SSLContextParameters` instance or through the `useGlobalSslContextParameters`
flag.

An MQTT connection keep alive timeout can be configured using `keepAliveTimeout`.

A delay can be added between Edge Node Rebirth publishing through the
`rebirthDebounceDelay` property.

=== Edge Node Endpoint Configuration

Sparkplug Edge Nodes are identified by a unique combination of Group ID and 
Edge Node ID, the Edge Node Descriptor. These two elements form the path
of an Edge Node Endpoint URI. All other Edge Node Endpoint configuration
properties use query string variables or are set via Endpoint property setters.

If an Edge Node is tied to a particular Host Application, the `primaryHostId`
query string variable can be set to enable the required Sparkplug behavior.

Metric aliasing is handled automatically by the Eclipse Tahu library and
enabled with the `useAliases` query string variable.

==== Birth/Death Sequence Numbers

The Sparkplug specification requires careful handling of NBIRTH/NDEATH sequence
numbers for Host Applications to correlate Edge Nodes' session behavior with
the metrics the Host Application receives.

By default, each Edge Node Endpoint writes a local file to store the next sequence number
that Edge Node should use when publishing its NBIRTH message and setting its NDEATH MQTT Will Message when establishing an MQTT Server connection. The local path for this file can be set using the `bdSeqNumPath` query string variable.

Should another Sparkplug spec-compliant Eclipse Tahu `BdSeqManager` instance be
required, use the `bdSeqManager` Endpoint property setter method.

=== Device Endpoint Configuration

Sparkplug Devices are identified by a unique combination of the Edge Node Descriptor
to which the Device is connected and the Device's Device ID. These three elements
form the path of a Device Endpoint URI. Since any Sparkplug Device is associated
with exactly one Edge Node, an MQTT Server connection and its associated Sparkplug
behavior is managed per Edge Node, not per Device. This means all Device Endpoint
configuration must be completed prior to starting the Edge Node Producer for a given
Device Endpoint.

=== Edge Node and Device Endpoint Interaction

Sparkplug Edge Nodes are not required to have a Device hierarchy and physical
devices may be represented directly as Edge Nodes--this decision is left to
Sparkplug application developers.

However if an Edge Node will be reporting Device-level metrics in addition to
and Edge Node-level metrics, the Edge Node Endpoint is required to have a 
`deviceIds` list configured to publish correct NBIRTH and DBIRTH payloads required
by the Sparkplug specification.

Additionally, a Tahu `SparkplugBPayloadMap` instance is required to be set
on each Edge Node and Device Endpoint to populate the NBIRTH/DBIRTH message 
with the required Sparkplug Metric names and data types. This is accomplished
using the `metricDataTypePayloadMap` Endpoint property setter method.

These requirements allow Sparkplug 3.0.0 compliant behavior.

// include::spring-boot:partial$starter.adoc[]
